services:

  api:
    image: azharfa/portfolio-api-api:latest
    container_name: portfolio_api
    restart: always
    ports:
      - "${PORT}:${INTERNAL_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - INTERNAL_PORT=${INTERNAL_PORT}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GIN_MODE=${GIN_MODE}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - PAYMENT_GATEWAY_URL=${PAYMENT_GATEWAY_URL}
      - PAYMENT_GATEWAY_API_KEY=${PAYMENT_GATEWAY_API_KEY}

    volumes:
      - ./uploads/portfolios:/app/uploads/portfolios

networks:
  default:
    external: true
    name: shared-network
